### ISSUE TITLE
nodejs version 6.10 no longer supported by aws

### ISSUE THREAD

**Issue by ramoriusvt** [sakazuki/aws-serverless-node-red#4]
When I attempted to run npm run setup, it failed and rolled back the CloudFormation stack because the cloudformation.yaml and packaged-seam.yaml both referred to "nodejs6.10". Changing these to "nodejs.10.x" worked, but I'm not sure if the dependencies were valid.

**Comment by sakazuki** [comment]
updated to nodejs12.x
